//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.IO;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace GridBlazorGrpc.Shared.Models
{
    [DataContract]
    public partial class Employee
    {
        private string _base64Str; 

        public Employee()
        {
            this.Orders = new HashSet<Order>();
            this.Territories = new HashSet<EmployeeTerritories>();
        }
        [Key]
        [DataMember(Order = 1)]
        public int EmployeeID { get; set; }
        [Required]
        [DataMember(Order = 2)]
        public string LastName { get; set; }
        [Required]
        [DataMember(Order = 3)]
        public string FirstName { get; set; }
        [DataMember(Order = 4)]
        public string Title { get; set; }
        [DataMember(Order = 5)]
        public string TitleOfCourtesy { get; set; }
        [DataMember(Order = 6)]
        public DateTime? BirthDate { get; set; }
        [DataMember(Order = 7)]
        public DateTime? HireDate { get; set; }
        [DataMember(Order = 8)]
        public string Address { get; set; }
        [DataMember(Order = 9)]
        public string City { get; set; }
        [DataMember(Order = 10)]
        public string Region { get; set; }
        [DataMember(Order = 11)]
        public string PostalCode { get; set; }
        [DataMember(Order = 12)]
        public string Country { get; set; }
        [DataMember(Order = 13)]
        public string HomePhone { get; set; }
        [DataMember(Order = 14)]
        public string Extension { get; set; }
        [JsonIgnore]
        public byte[] Photo { get; set; }
        [DataMember(Order = 15)]
        public string Notes { get; set; }
        [DataMember(Order = 16)]
        public Nullable<int> ReportsTo { get; set; }
        [DataMember(Order = 17)]
        public string PhotoPath { get; set; }

        [JsonIgnore]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<EmployeeTerritories> Territories { get; set; }

        [NotMapped]
        [DataMember(Order = 18)]
        public string Base64String
        {
            get
            {
                if (string.IsNullOrWhiteSpace(_base64Str))
                {
                    _base64Str = string.Empty;
                    if (Photo != null)
                    {
                        using (var ms = new MemoryStream())
                        {
                            int offset = 78;
                            ms.Write(Photo, offset, Photo.Length - offset);
                            _base64Str = Convert.ToBase64String(ms.ToArray());
                        }
                    }
                }
                return _base64Str;
            }
            set
            {
                _base64Str = value;
            }
        }
    }
}
