//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace GridBlazorGrpc.Shared.Models
{
    [Table("Order Details")]
    [DataContract]
    public partial class OrderDetail
    {
        [DataMember(Order = 1)]
        public int OrderID { get; set; }
        [DataMember(Order = 2)]
        public int ProductID { get; set; }
        [DataMember(Order = 3)]
        public decimal UnitPrice { get; set; }
        [DataMember(Order = 4)]
        public short Quantity { get; set; }
        [Range(0, 1, ErrorMessage = "Discount must be between 0 and 1.")]
        [DataMember(Order = 5)]
        public float Discount { get; set; }
        [ForeignKey("OrderID")]
        [JsonIgnore]
        public virtual Order Order { get; set; }
        [ForeignKey("ProductID")]
        [DataMember(Order = 6)]
        public virtual Product Product { get; set; }
    }
}
