//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace GridBlazorGrpc.Shared.Models
{
    [DataContract]
    public partial class Product
    {
        public Product()
        {
            this.Order_Details = new HashSet<OrderDetail>();
        }
        [Key]
        [DataMember(Order = 1)]
        public int ProductID { get; set; }
        [DataMember(Order = 2)]
        public string ProductName { get; set; }
        [DataMember(Order = 3)]
        public Nullable<int> SupplierID { get; set; }
        [DataMember(Order = 4)]
        public Nullable<int> CategoryID { get; set; }
        [DataMember(Order = 5)]
        public string QuantityPerUnit { get; set; }
        [DataMember(Order = 6)]
        public Nullable<decimal> UnitPrice { get; set; }
        [DataMember(Order = 7)]
        public Nullable<short> UnitsInStock { get; set; }
        [DataMember(Order = 8)]
        public Nullable<short> UnitsOnOrder { get; set; }
        [DataMember(Order = 9)]
        public Nullable<short> ReorderLevel { get; set; }
        [DataMember(Order = 10)]
        public bool Discontinued { get; set; }
        [DataMember(Order = 11)]
        public virtual Category Category { get; set; }
        [JsonIgnore]
        public virtual ICollection<OrderDetail> Order_Details { get; set; }
        [DataMember(Order = 12)]
        public virtual Supplier Supplier { get; set; }
    }
}
