//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace GridBlazorGrpc.Shared.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Supplier
    {
        public Supplier()
        {
            this.Products = new HashSet<Product>();
        }
        [Key]
        [DataMember(Order = 1)]
        public int SupplierID { get; set; }
        [DataMember(Order = 2)]
        public string CompanyName { get; set; }
        [DataMember(Order = 3)]
        public string ContactName { get; set; }
        [DataMember(Order = 4)]
        public string ContactTitle { get; set; }
        [DataMember(Order = 5)]
        public string Address { get; set; }
        [DataMember(Order = 6)]
        public string City { get; set; }
        [DataMember(Order = 7)]
        public string Region { get; set; }
        [DataMember(Order = 8)]
        public string PostalCode { get; set; }
        [DataMember(Order = 9)]
        public string Country { get; set; }
        [DataMember(Order = 10)]
        public string Phone { get; set; }
        [DataMember(Order = 11)]
        public string Fax { get; set; }
        [DataMember(Order = 12)]
        public string HomePage { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
