// <auto-generated />
namespace GridBlazor.Resources
{
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Globalization;
    using System.Reflection;
    using System.Resources;
    using System.Runtime.CompilerServices;

    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [SuppressMessage("Microsoft.Design", "CA1053:StaticHolderTypesShouldNotHaveConstructors")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Strings
    {
        /// <summary>
        /// The resource manager.
        /// </summary>
        private static ResourceManager resourceManager;

        /// <summary>
        /// Initializes a new instance of the <see cref="Strings"/> class.
        /// </summary>
        public Strings()
        {
        }

        /// <summary>
        /// Gets the resource string indexed by the ApplyFilterButtonText key.
        /// </summary>
        public static string ApplyFilterButtonText
        {
            get
            {
                return Strings.ResourceManager.GetString("ApplyFilterButtonText", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the BoolFalseLabel key.
        /// </summary>
        public static string BoolFalseLabel
        {
            get
            {
                return Strings.ResourceManager.GetString("BoolFalseLabel", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the BoolTrueLabel key.
        /// </summary>
        public static string BoolTrueLabel
        {
            get
            {
                return Strings.ResourceManager.GetString("BoolTrueLabel", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the ClearFilterLabel key.
        /// </summary>
        public static string ClearFilterLabel
        {
            get
            {
                return Strings.ResourceManager.GetString("ClearFilterLabel", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Contains key.
        /// </summary>
        public static string Contains
        {
            get
            {
                return Strings.ResourceManager.GetString("Contains", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets or sets the culture to use for lookups using this strongly typed resource class.
        /// </summary>
        public static CultureInfo CultureInfo { get; set; }

        /// <summary>
        /// Gets the resource string indexed by the DefaultGridEmptyText key.
        /// </summary>
        public static string DefaultGridEmptyText
        {
            get
            {
                return Strings.ResourceManager.GetString("DefaultGridEmptyText", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the EndsWith key.
        /// </summary>
        public static string EndsWith
        {
            get
            {
                return Strings.ResourceManager.GetString("EndsWith", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Equal key.
        /// </summary>
        public static string Equal
        {
            get
            {
                return Strings.ResourceManager.GetString("Equal", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the FilterButtonTooltipText key.
        /// </summary>
        public static string FilterButtonTooltipText
        {
            get
            {
                return Strings.ResourceManager.GetString("FilterButtonTooltipText", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the FilterTypeLabel key.
        /// </summary>
        public static string FilterTypeLabel
        {
            get
            {
                return Strings.ResourceManager.GetString("FilterTypeLabel", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the FilterValueLabel key.
        /// </summary>
        public static string FilterValueLabel
        {
            get
            {
                return Strings.ResourceManager.GetString("FilterValueLabel", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the GreaterThan key.
        /// </summary>
        public static string GreaterThan
        {
            get
            {
                return Strings.ResourceManager.GetString("GreaterThan", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the GreaterThanOrEquals key.
        /// </summary>
        public static string GreaterThanOrEquals
        {
            get
            {
                return Strings.ResourceManager.GetString("GreaterThanOrEquals", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Items key.
        /// </summary>
        public static string Items
        {
            get
            {
                return Strings.ResourceManager.GetString("Items", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Lang key.
        /// </summary>
        public static string Lang
        {
            get
            {
                return Strings.ResourceManager.GetString("Lang", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the LessThan key.
        /// </summary>
        public static string LessThan
        {
            get
            {
                return Strings.ResourceManager.GetString("LessThan", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the LessThanOrEquals key.
        /// </summary>
        public static string LessThanOrEquals
        {
            get
            {
                return Strings.ResourceManager.GetString("LessThanOrEquals", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the cached ResourceManager instance used by this class.
        /// </summary>
        public static ResourceManager ResourceManager
        {
            get
            {
                if (Strings.resourceManager == null)
                {
                    Strings.resourceManager = new ResourceManager("GridBlazor.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                }

                return Strings.resourceManager;
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the SearchFor key.
        /// </summary>
        public static string SearchFor
        {
            get
            {
                return Strings.ResourceManager.GetString("SearchFor", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the StartsWith key.
        /// </summary>
        public static string StartsWith
        {
            get
            {
                return Strings.ResourceManager.GetString("StartsWith", Strings.CultureInfo);
            }
        }
    }
}