//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridBlazor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GridBlazor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ApplyFilterButtonText {
            get {
                return ResourceManager.GetString("ApplyFilterButtonText", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string BoolFalseLabel {
            get {
                return ResourceManager.GetString("BoolFalseLabel", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string BoolTrueLabel {
            get {
                return ResourceManager.GetString("BoolTrueLabel", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all filters.
        /// </summary>
        public static string ClearAllFilters {
            get {
                return ResourceManager.GetString("ClearAllFilters", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filter.
        /// </summary>
        public static string ClearFilterLabel {
            get {
                return ResourceManager.GetString("ClearFilterLabel", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Code.
        /// </summary>
        public static string Confirm_Code {
            get {
                return ResourceManager.GetString("Confirm Code", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code and confirmation code must be equal to save this item.
        /// </summary>
        public static string ConfirmCodeError {
            get {
                return ResourceManager.GetString("ConfirmCodeError", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string Contains {
            get {
                return ResourceManager.GetString("Contains", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating the new item.
        /// </summary>
        public static string CreateError {
            get {
                return ResourceManager.GetString("CreateError", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create item.
        /// </summary>
        public static string CreateItem {
            get {
                return ResourceManager.GetString("CreateItem", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items to display.
        /// </summary>
        public static string DefaultGridEmptyText {
            get {
                return ResourceManager.GetString("DefaultGridEmptyText", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code and confirmation code must be equal to delete this item.
        /// </summary>
        public static string DeleteConfirmCodeError {
            get {
                return ResourceManager.GetString("DeleteConfirmCodeError", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error deleting this item.
        /// </summary>
        public static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete item.
        /// </summary>
        public static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        public static string EndsWith {
            get {
                return ResourceManager.GetString("EndsWith", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        public static string Equal {
            get {
                return ResourceManager.GetString("Equal", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop columns here for column extended sorting.
        /// </summary>
        public static string ExtSortingText {
            get {
                return ResourceManager.GetString("ExtSortingText", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter this column.
        /// </summary>
        public static string FilterButtonTooltipText {
            get {
                return ResourceManager.GetString("FilterButtonTooltipText", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string FilterTypeLabel {
            get {
                return ResourceManager.GetString("FilterTypeLabel", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string FilterValueLabel {
            get {
                return ResourceManager.GetString("FilterValueLabel", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to.
        /// </summary>
        public static string Goto {
            get {
                return ResourceManager.GetString("Goto", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than.
        /// </summary>
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than or equals.
        /// </summary>
        public static string GreaterThanOrEquals {
            get {
                return ResourceManager.GetString("GreaterThanOrEquals", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop columns here for column grouping.
        /// </summary>
        public static string GroupingText {
            get {
                return ResourceManager.GetString("GroupingText", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not null.
        /// </summary>
        public static string IsNotNull {
            get {
                return ResourceManager.GetString("IsNotNull", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is null.
        /// </summary>
        public static string IsNull {
            get {
                return ResourceManager.GetString("IsNull", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than.
        /// </summary>
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than or equals.
        /// </summary>
        public static string LessThanOrEquals {
            get {
                return ResourceManager.GetString("LessThanOrEquals", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not equals.
        /// </summary>
        public static string NotEqual {
            get {
                return ResourceManager.GetString("NotEqual", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read item.
        /// </summary>
        public static string ReadItem {
            get {
                return ResourceManager.GetString("ReadItem", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search phrase.
        /// </summary>
        public static string SearchFilterListInputText {
            get {
                return ResourceManager.GetString("SearchFilterListInputText", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for ....
        /// </summary>
        public static string SearchFor {
            get {
                return ResourceManager.GetString("SearchFor", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select the row you want to delete.
        /// </summary>
        public static string SelectionDeleteError {
            get {
                return ResourceManager.GetString("SelectionDeleteError", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select the row you want to view.
        /// </summary>
        public static string SelectionReadError {
            get {
                return ResourceManager.GetString("SelectionReadError", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select the row you want to edit.
        /// </summary>
        public static string SelectionUpdateError {
            get {
                return ResourceManager.GetString("SelectionUpdateError", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select an item ---.
        /// </summary>
        public static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        public static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error updating this item.
        /// </summary>
        public static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update item.
        /// </summary>
        public static string UpdateItem {
            get {
                return ResourceManager.GetString("UpdateItem", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", System.Globalization.CultureInfo.CurrentCulture);
            }
        }
    }
}
