<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Version>6.2.0</Version>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.ObjectPool" Version="10.0.5" />
		<PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
		<PackageReference Include="System.Formats.Asn1" Version="10.0.5" />
		<PackageReference Include="System.Security.Cryptography.Pkcs" Version="10.0.6" />
		<PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.6" />
		<PackageReference Include="System.ServiceModel.Primitives" Version="10.0.652802" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\GridShared\GridShared.csproj" />
	</ItemGroup>

</Project>