// <auto-generated />
namespace GridMvc.Resources
{
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Globalization;
    using System.Reflection;
    using System.Resources;
    using System.Runtime.CompilerServices;

    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [SuppressMessage("Microsoft.Design", "CA1053:StaticHolderTypesShouldNotHaveConstructors")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Strings
    {
        /// <summary>
        /// The resource manager.
        /// </summary>
        private static ResourceManager resourceManager;

        /// <summary>
        /// Initializes a new instance of the <see cref="Strings"/> class.
        /// </summary>
        public Strings()
        {
        }

        /// <summary>
        /// Gets or sets the culture to use for lookups using this strongly typed resource class.
        /// </summary>
        public static CultureInfo CultureInfo { get; set; }

        /// <summary>
        /// Gets the resource string indexed by the Average key.
        /// </summary>
        public static string Average
        {
            get
            {
                return Strings.ResourceManager.GetString("Average", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the DefaultGridEmptyText key.
        /// </summary>
        public static string DefaultGridEmptyText
        {
            get
            {
                return Strings.ResourceManager.GetString("DefaultGridEmptyText", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the FilterButtonTooltipText key.
        /// </summary>
        public static string FilterButtonTooltipText
        {
            get
            {
                return Strings.ResourceManager.GetString("FilterButtonTooltipText", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Items key.
        /// </summary>
        public static string Items
        {
            get
            {
                return Strings.ResourceManager.GetString("Items", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Lang key.
        /// </summary>
        public static string Lang
        {
            get
            {
                return Strings.ResourceManager.GetString("Lang", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Max key.
        /// </summary>
        public static string Max
        {
            get
            {
                return Strings.ResourceManager.GetString("Max", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Min key.
        /// </summary>
        public static string Min
        {
            get
            {
                return Strings.ResourceManager.GetString("Min", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the cached ResourceManager instance used by this class.
        /// </summary>
        public static ResourceManager ResourceManager
        {
            get
            {
                if (Strings.resourceManager == null)
                {
                    Strings.resourceManager = new ResourceManager("GridMvc.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                }

                return Strings.resourceManager;
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the SearchFor key.
        /// </summary>
        public static string SearchFor
        {
            get
            {
                return Strings.ResourceManager.GetString("SearchFor", Strings.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Sum key.
        /// </summary>
        public static string Sum
        {
            get
            {
                return Strings.ResourceManager.GetString("Sum", Strings.CultureInfo);
            }
        }
    }
}