//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GridShared.DataAnnotations;
using GridShared.Sorting;
using GridMvc.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GridMvc.Demo.Models
{
    public class OrderMetaData
    {
        [Display(Name = "Ship name", AutoGenerateFilter = true)]
        public string ShipName { get; set; }
    }

    [ModelMetadataTypeAttribute(typeof(OrderMetaData))]
    [GridTable(PagingEnabled = true, PageSize = 20)]
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
        [Key]
        [GridHiddenColumn]
        public int OrderID { get; set; }

        [NotMappedColumn]
        public string CustomerID { get; set; }
        [NotMappedColumn]
        public int? EmployeeID { get; set; }
        [GridColumn(Title = "Date", Width = "120px", Format = "{0:yyyy-MM-dd}", SortEnabled = true, FilterEnabled = true, SortInitialDirection = GridSortDirection.Descending)]
        public DateTime? OrderDate { get; set; }
        [NotMappedColumn]
        public DateTime? RequiredDate { get; set; }
        [NotMappedColumn]
        public DateTime? ShippedDate { get; set; }
        [NotMappedColumn]
        public int? ShipVia { get; set; }
        [GridColumn(Title = "Freight", Width = "120px", SortEnabled = true, FilterEnabled = true)]
        public decimal? Freight { get; set; }

        public string ShipName { get; set; }
        [NotMappedColumn]
        public string ShipAddress { get; set; }
        [NotMappedColumn]
        public string ShipCity { get; set; }
        [NotMappedColumn]
        public string ShipRegion { get; set; }
        [NotMappedColumn]
        public string ShipPostalCode { get; set; }
        [NotMappedColumn]
        public string ShipCountry { get; set; }
        [NotMappedColumn]
        public virtual Customer Customer { get; set; }
        [NotMappedColumn]
        public virtual Employee Employee { get; set; }
        [NotMappedColumn]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }

        //public virtual Shipper Shipper { get; set; }
    }

}
